spring.application.name=campusconnect

<<<<<<< HEAD
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
=======
spring.datasource.url=dbc:mysql://your-host:3306/your-db
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
>>>>>>> 8cf3b374ed00dacffb55002cb0bdcdbd9a2c3517

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omindupeter@gmail.com
spring.mail.password=atgg ayzv hrcn fgiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
